apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Cert-Manager (required)
- ../dist/stacks/ibm/application/cert-manager
# Istio (requires)
- ../dist/stacks/ibm/application/istio
# OIDC Authservice (required)
- ../dist/stacks/ibm/application/oidc-authservice-appid
# Knative
- ../dist/stacks/ibm/application/knative
# Kubeflow namespace (required)
- ../dist/stacks/ibm/application/kubeflow-namespace
# Kubeflow Roles (required)
- ../dist/stacks/ibm/application/kubeflow-roles
# Kubeflow istio resource (required)
- ../dist/stacks/ibm/application/kubeflow-istio-resources
# Central Dashboard (required)
- ../dist/stacks/ibm/application/centraldashboard/multi-user
# Admission Webhook (required)
- ../dist/stacks/ibm/application/admission-webhook
# Profiles + KFAM (required)
- ../dist/stacks/ibm/application/profiles
# Kubeflow Pipelines Tekton
- ../dist/stacks/ibm/application/kfp-tekton
# For KFP-Tekton V1, replace the Kubeflow Pipelines Tekton V2 stack above to the V1 stack below
# - ../dist/stacks/ibm/application/kfp-tekton-v1
# KServe
- ../dist/stacks/ibm/application/kserve
# Katib
- ../dist/stacks/ibm/application/katib
# Notebook Controller
- ../dist/stacks/ibm/application/notebook-controller
# Jupyter Web App
- ../dist/stacks/ibm/application/jupyter-web-app/insecure
# Volumes Web App
- ../dist/stacks/ibm/application/volumes-web-app/insecure
# Tensorboards Web App
-  ../dist/stacks/ibm/application/tensorboard-web-app/insecure
# Tensorboard Controller
-  ../dist/stacks/ibm/application/tensorboard-controller
# Training Operator
- ../dist/stacks/ibm/application/training-operator

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration
