apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Cert-Manager (required)
- ../dist/stacks/ibm/application/cert-manager
# Istio (requires)
- ../dist/stacks/ibm/application/istio
# OIDC Authservice (required)
- ../dist/stacks/ibm/application/oidc-authservice-appid
# Knative
- ../dist/stacks/ibm/application/knative
# Kubeflow namespace (required)
- ../dist/stacks/ibm/application/kubeflow-namespace
# Kubeflow Roles (required)
- ../dist/stacks/ibm/application/kubeflow-roles
# Kubeflow istio resource (required)
- ../dist/stacks/ibm/application/kubeflow-istio-resources
# Kubeflow Pipelines Tekton
- ../dist/stacks/ibm/application/kfp-tekton
# KServe
- ../dist/stacks/ibm/application/kserve
# Katib
- ../dist/stacks/ibm/application/katib
# Central Dashboard (required)
- ../dist/stacks/ibm/application/centraldashboard/multi-user
# Admission Webhook (required)
- ../dist/stacks/ibm/application/admission-webhook
# Notebook Controller
- ../dist/stacks/ibm/application/notebook-controller
# Jupyter Web App
- ../dist/stacks/ibm/application/jupyter-web-app/insecure
# Profiles + KFAM (required)
- ../dist/stacks/ibm/application/profiles
# Volumes Web App
- ../dist/stacks/ibm/application/volumes-web-app/insecure
# Tensorboards Web App
-  ../dist/stacks/ibm/application/tensorboard-web-app/insecure
# Tensorboard Controller
-  ../dist/stacks/ibm/application/tensorboard-controller
# Training Operator
- ../dist/stacks/ibm/application/training-operator

images:
- name: docker.io/aipipeline/api-server
  newName: quay.io/aipipeline/api-server
  newTag: 1.5.1
- name: docker.io/aipipeline/persistenceagent
  newName: quay.io/aipipeline/persistenceagent
  newTag: 1.5.1
- name: docker.io/aipipeline/scheduledworkflow
  newName: quay.io/aipipeline/scheduledworkflow
  newTag: 1.5.1
- name: docker.io/aipipeline/cache-server
  newName: quay.io/aipipeline/cache-server
  newTag: 1.5.1
- name: docker.io/aipipeline/metadata-writer
  newName: quay.io/aipipeline/metadata-writer
  newTag: 1.5.1
- name: docker.io/aipipeline/frontend
  newName: quay.io/aipipeline/frontend
  newTag: 1.5.1
- name: docker.io/aipipeline/pipelineloop-controller
  newName: quay.io/aipipeline/pipelineloop-controller
  newTag: 1.5.1
- name: docker.io/aipipeline/pipelineloop-webhook
  newName: quay.io/aipipeline/pipelineloop-webhook
  newTag: 1.5.1
