apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Cert-Manager (required)
- ../dist/stacks/ibm/application/cert-manager
# Istio (requires)
- ../dist/stacks/ibm/application/istio-1-11
# OIDC Authservice (required)
- ../dist/stacks/ibm/application/oidc-authservice
- ../dist/stacks/ibm/application/dex-auth
# Knative
- ../dist/stacks/ibm/application/knative
# Kubeflow namespace (required)
- ../dist/stacks/ibm/application/kubeflow-namespace
# Kubeflow Roles (required)
- ../dist/stacks/ibm/application/kubeflow-roles
# Kubeflow istio resource (required)
- ../dist/stacks/ibm/application/kubeflow-istio-resources
# Kubeflow Pipelines Tekton
- ../dist/stacks/ibm/application/kfp-tekton
# KServe
- ../dist/stacks/ibm/application/kserve
# Katib
- ../dist/stacks/ibm/application/katib
# Central Dashboard (required)
- ../dist/stacks/ibm/application/centraldashboard/single-user
# Admission Webhook (required)
- ../dist/stacks/ibm/application/admission-webhook
# Notebook Controller
- ../dist/stacks/ibm/application/notebook-controller
# Jupyter Web App
- ../dist/stacks/ibm/application/jupyter-web-app/insecure
# Profiles + KFAM (required)
- ../dist/stacks/ibm/application/profiles
- ../dist/stacks/ibm/application/user-namespace
# Volumes Web App
- ../dist/stacks/ibm/application/volumes-web-app/insecure
# Tensorboards Web App
-  ../dist/stacks/ibm/application/tensorboard-web-app/insecure
# Tensorboard Controller
-  ../dist/stacks/ibm/application/tensorboard-controller
# Training Operator
- ../dist/stacks/ibm/application/training-operator
