# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/mlx-deployments
  - ../base/mlx-vs
resources:
  - kfp-vs.yaml
  - clusterrolebinding.yaml
  - secrets.yaml
patchesStrategicMerge:
  - mlx-ui-patch.yaml
