baseURL = "https://ibm.github.io/manifests"
title = "Kubeflow on IKS"
description = "Kubeflow Deployment on IBM Cloud Kubernetes Service"

enableRobotsTXT = true

theme = ["docsy"]

###############################################################################
# Docsy
###############################################################################
enableGitInfo = false

# language settings
contentDir = "content/en"
defaultContentLanguage = "en"
# tell Hugo not to include the /en/ element in the URL path for English docs
defaultContentLanguageInSubdir = false
# useful when translating
enableMissingTranslationPlaceholders = true
# disable taxonomies
disableKinds = ["taxonomy", "taxonomyTerm"]

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################
[menu]
  [[menu.main]]
    name = "GitHub"
    weight = 40
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/IBM/manifests"

###############################################################################
# Docsy - Goldmark markdown parser
###############################################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = 'tango'
    guessSyntax = false
    lineNumbersInTable = true
    noClasses = false
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false

###############################################################################
# Docsy - Image processing configuration
###############################################################################
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

###############################################################################
# Docsy - Language configuration
###############################################################################
[languages]
  [languages.en]
    title = "Kubeflow on IKS"
    description = "Kubeflow Deployment on IBM Cloud Kubernetes Service"
    languageName ="English"
    # weight used for sorting in the language menu
    weight = 1

###############################################################################
# Docsy - Site Parameters
###############################################################################
[params]
  github_repo = "https://github.com/IBM/manifests"
  github_subdir = "website"
  github_branch = "github-pages"
  github_project_repo = "https://github.com/IBM/manifests"

  RSSLink = "/index.xml"
  author = "https://ibm.github.io/" # add your company name
  github = "Kubeflow in IBM" # add your github profile name

  copyright = "The Kubeflow Authors."
  privacy_policy = "https://www.ibm.com/us-en/privacy"

  # Text label for the version menu in the top bar of the website.
  version_menu = "Release Version"

  # The major.minor version tag for the version of the docs represented in this
  # branch of the repository. Used in the "version-banner" partial to display a
  # version number for this doc set.
  version = "master"

  # Flag used in the "version-banner" partial to decide whether to display a
  # banner on every page indicating that this is an archived version of the docs.
  archived_version = false

  # A link to latest version of the docs. Used in the "version-banner" partial to
  # point people to the main doc site.
  url_latest_version = "https://ibm.github.io/manifests/docs/"

  # A variable used in various docs to determine URLs for config files etc.
  # To find occurrences, search the repo for 'params "githubbranch"'.
  githubbranch = "master"

  # These entries appear in the drop-down menu at the top of the website.
  [[params.versions]]
    version = "latest"
    githubbranch = "v1.8-branch"
    url = "/manifests/"
  [[params.versions]]
    version = "v1.8"
    githubbranch = "v1.8-branch"
    url = "/manifests/"
  [[params.versions]]
    version = "v1.7"
    githubbranch = "v1.7-branch"
    url = "/manifests/release/v1.7"
  [[params.versions]]
    version = "v1.6"
    githubbranch = "v1.6-branch"
    url = "/manifests/release/v1.6"


  # User interface configuration
  [params.ui]
    # Enable the logo
    navbar_logo = false
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    # Enable the search box in the side bar.
    sidebar_search_disable = false
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Show expand/collapse icon for sidebar sections
    sidebar_menu_foldable = true
    # Disable about button in footer
    footer_about_disable = true

      # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
      # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
      # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
      # add "hide_feedback: true" to the page's front matter.
      [params.ui.feedback]
        enable = true
        # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
        yes = 'Glad to hear it! Please <a href="https://github.com/IBM/manifests/issues/new">tell us how we can improve</a>.'
        no = 'Sorry to hear that. Please <a href="https://github.com/IBM/manifests/issues/new">tell us how we can improve</a>.'

# hugo module configuration
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

